### ISSUE TITLE
PUBG code review

### ISSUE THREAD

**Issue by thalassophilia** [geum-yong/PUBG_Clone#1]
같은 페이지를 클론 코딩한 입장에서 적어보는 코드리뷰입니다.

- [x]  헤더 부분에서 화면크기 1261px까지는 pc화면을 제공하고 그 이하로는 모바일 화면을 제공합니다. 화면 크기 1024px 이용자를 고려하지 않는다쳐도 1440px 사용자가 화면 크기를 조금만 줄여도 상단의 메뉴들이 사라집니다. 이는 소비자에게 혼란을 줄 수 있다고 생각
- [x]  patch notes의 이미지 대체텍스트 제공하지 않음
- [x]  푸터 영역의 이미지 대체텍스트 내용과다 - 대체텍스트의 내용이 많을 경우 제목정도만 제공하고 숨김컨텐츠로 내용을 전달해야함, 대체텍스트는 항상 임팩트있게 작성할 것, 또 텝 접근이 불가하여 대체텍스트를 적었음에도 불구하고 스크린리더가 읽지 못함
- [x] 태그선택 과다이용

**Comment by geum-yong** [comment]
감사합니다. 코드 수정했습니다.
